[package]
name = "rusty18n"
version = "0.1.7"
edition = "2021"

repository = "https://github.com/o-dasher/rusty18n.git"
description = "A simply yet efficient i18n solution for Rust."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy_reflect = {version="0.12.1", optional=true}

[workspace]
members = [
    "example",
]
