[package]
name = "rusty18n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_reflect = "0.12.1"

[workspace]
members = [
    "example"
]
