[package]
name = "rusty18n"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/o-dasher/rusty18n.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_reflect = "0.12.1"
deep-struct-update = "0.1.0"

[workspace]
members = [
    "example",
]
